stages:
 - stage: check
   displayName: Compilation check
   jobs:
     - template: azure/cargo-check.yml@templates
       parameters:
         rust: nightly
         name: cargo_check
 - stage: test
   displayName: Test suite
   dependsOn: check
   jobs:
     - template: azure/tests.yml@templates
       parameters:
         rust: nightly
 - stage: style
   displayName: Style linting
   dependsOn: check
   jobs:
     - template: azure/style.yml@templates
       parameters:
         rust: nightly

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: gardnervickers
