stages:
 - stage: check
   displayName: Compilation check
   jobs:
     - template: azure/cargo-check.yml@templates
       parameters:
         rust: nightly
         name: cargo_check
 - stage: test
   displayName: Test suite
   dependsOn: check
   jobs:
     - template: azure/test.yml@templates
       parameters:
         rust: nightly

 - stage: style
   displayName: Style linting
   dependsOn: check
   jobs:
     - template: azure/rustfmt.yml@templates
       parameters:
         name: rustfmt
         rust: nightly
     - template: azure/cargo-clippy.yml@templates
       parameters:
         name: clippy
         rust: nightly

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: gardnervickers
